/*
 * Mandatory exercise 1
 *
 * Mandatory exercse 1
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type User struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name"`

	Mail string `json:"mail"`

	Popularity int64 `json:"popularity,omitempty"`

	Role string `json:"role"`
}
