/*
 * Mandatory exercise 1
 *
 * Mandatory exercse 1
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"github.com/ArneProductions/DISYS-exercise-1/models"
	"log"
)

func main() {
	log.Printf("Server started")

	db, _ := models.OpenDbConnection()

	SetupRouter(db)
}
