/*
 * Mandatory exercise 1
 *
 * Mandatory exercse 1
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

import (
	"gorm.io/gorm"
	"time"
)

type User struct {
	ID         uint64         `json:"id,omitempty" gorm:"primaryKey;autoIncrement"`
	Name       string         `json:"name"`
	Mail       string         `json:"mail"`
	Popularity int64          `json:"popularity,omitempty"`
	Role       string         `json:"role"`
	CreatedAt  time.Time      `json:"created_at,omitempty"`
	UpdatedAt  time.Time      `json:"updated_at,omitempty"`
	DeletedAt  gorm.DeletedAt `json:"deleted_at,omitempty" gorm:"index"`
}
