/*
 * Mandatory exercise 1
 *
 * Mandatory exercse 1
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package endpoints

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type SatisfactionController interface {
	GetCourseSatisfaction(ctx *gin.Context)
	AddSatisfaction(ctx *gin.Context)
	GetStudentSatisfaction(ctx *gin.Context)
}

type satisfactionController struct {
}

func NewSatisfactionController() SatisfactionController {
	return satisfactionController{}
}

func (s satisfactionController) GetCourseSatisfaction(ctx *gin.Context) {
	ctx.JSON(http.StatusOK, gin.H{"msg": "Ok"})
}

func (s satisfactionController) AddSatisfaction(ctx *gin.Context) {
	ctx.JSON(http.StatusOK, gin.H{"msg": "Ok"})
}

func (s satisfactionController) GetStudentSatisfaction(ctx *gin.Context) {
	ctx.JSON(http.StatusOK, gin.H{"msg": "Ok"})
}
