/*
 * Mandatory exercise 1
 *
 * Mandatory exercse 1
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package endpoints

import (
	"github.com/gin-gonic/gin"
	"net/http"
)

type WorkloadController interface {
	GetStudentWorkloadFromCourse(*gin.Context)
	AddWorkload(*gin.Context)
}

type workloadController struct {
}

func NewWorkloadController() WorkloadController {
	return workloadController{}
}

func (w workloadController) GetStudentWorkloadFromCourse(ctx *gin.Context) {
	ctx.JSON(http.StatusOK, gin.H{"msg": "Ok"})
}

func (w workloadController) AddWorkload(ctx *gin.Context) {
	ctx.JSON(http.StatusOK, gin.H{"msg": "Ok"})
}
