/*
 * Mandatory exercise 1
 *
 * Mandatory exercse 1
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package endpoints

import (
	"net/http"

	"github.com/ArneProductions/DISYS-exercise-1/repository"
	"github.com/gin-gonic/gin"
)

type CourseController interface {
	AddCourse(*gin.Context)
	AddStudentsToCourse(*gin.Context)
	DeleteCourse(*gin.Context)
	GetCourses(*gin.Context)
	RemoveStudentFromCourse(*gin.Context)
}

type courseController struct {
	courseRepository repository.CourseRepository
}

func NewCourseController(repo repository.CourseRepository) CourseController {
	return courseController{courseRepository: repo}
}

func (c courseController) AddCourse(ctx *gin.Context) {
	ctx.JSON(http.StatusOK, gin.H{"msg": "Ok"})
}

func (c courseController) AddStudentsToCourse(ctx *gin.Context) {
	ctx.JSON(http.StatusOK, gin.H{"msg": "Ok"})
}

func (c courseController) DeleteCourse(ctx *gin.Context) {
	ctx.JSON(http.StatusOK, gin.H{"msg": "Ok"})
}

func (c courseController) GetCourses(ctx *gin.Context) {
	ctx.JSON(http.StatusOK, gin.H{"msg": "Ok"})
}

func (c courseController) RemoveStudentFromCourse(ctx *gin.Context) {
	ctx.JSON(http.StatusOK, gin.H{"msg": "Ok"})
}
