/*
 * Mandatory exercise 1
 *
 * Mandatory exercse 1
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

type StudentWorkload struct {
	WorkloadId int64 `json:"workload_id,omitempty"`

	StudentId int64 `json:"student_id,omitempty"`

	Completion int64 `json:"completion,omitempty"`
}
