/*
 * Mandatory exercise 1
 *
 * Mandatory exercse 1
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

type StudentSatisfaction struct {
	CourseId int64 `json:"course_id,omitempty"`

	StudentId int64 `json:"student_id,omitempty"`

	Satisfaction int64 `json:"satisfaction,omitempty"`
}
